version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      github-actions-dependencies:
        patterns:
          - "*"

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      angular-stack-dependencies:
        patterns:
          - "@angular/*"
          - "angular-eslint"
          - "typescript"
          - "typescript-eslint"
        update-types:
          - "major"
          - "minor"
          - "patch"
      npm-non-angular-dependencies:
        patterns:
          - "*"
        exclude-patterns:
          - "@angular/*"
          - "angular-eslint"
          - "typescript"
          - "typescript-eslint"
        update-types:
          - "minor"
          - "patch"